name: Build Jupyter Book

on:
  push:
    branches:
      - main
    paths:
      - 'notebooks/**/*.ipynb'
      - 'docs/**/*.md'
      - '_config.yml'
      - '_toc.yml'
      - '.github/workflows/publish-notebooks.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install "jupyter-book>=0.15,<2" ghp-import

      - name: Build the book
        run: jupyter-book build .

      - name: Push to GitHub Pages
        if: github.ref == 'refs/heads/main'
        run: |
          ghp-import -n -p -f _build/html
